# Generated by Django 4.2 on 2023-10-27 11:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('number_account', models.CharField(max_length=20)),
                ('index', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_business', to='authentication.userbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_document_business', to='authentication.userbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_finance_business', to='authentication.userbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_business', to='authentication.userbusiness')),
                ('category_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_category_document', to='finance.categorydocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=255)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry_business', to='authentication.userbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_credit', to='finance.categoryfinance')),
                ('debit_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_debit', to='finance.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry_line_account', to='finance.account')),
                ('journal_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry_line_journal_entry', to='finance.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('descripción', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_account', to='finance.account')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_business', to='authentication.userbusiness')),
                ('category_finance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_category_finance', to='finance.categoryfinance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('descripción', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_file', models.ImageField(null=True, upload_to='expenses/')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_account', to='finance.account')),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_business', to='authentication.userbusiness')),
                ('category_finance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_category_finance', to='finance.categoryfinance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_detail_account', to='finance.account')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_detail_document', to='finance.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_id', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_account', to='finance.account')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_business', to='authentication.userbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
