# Generated by Django 4.2 on 2023-10-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfinance',
            name='credit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_finance_credit', to='finance.account'),
        ),
        migrations.AddField(
            model_name='categoryfinance',
            name='debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_finance_debit', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_credit', to='finance.account'),
        ),
    ]
