# Generated by Django 4.2 on 2023-10-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_useradmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='business_user', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_user', to='authentication.user'),
        ),
    ]
